# Generated by Django 2.1.4 on 2019-08-26 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='jump date')),
                ('number', models.IntegerField(default=0)),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Jumper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='JumpKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('height', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=250)),
                ('kind', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='jump',
            name='jump_kind_id',
            field=models.ForeignKey(db_column='jump_kind_id', on_delete=django.db.models.deletion.CASCADE, to='jtl_app.JumpKind'),
        ),
        migrations.AddField(
            model_name='jump',
            name='jumper_id',
            field=models.ForeignKey(db_column='jumper_id', on_delete=django.db.models.deletion.CASCADE, to='jtl_app.Jumper'),
        ),
        migrations.AddField(
            model_name='jump',
            name='spot_id',
            field=models.ForeignKey(db_column='spot_id', on_delete=django.db.models.deletion.CASCADE, to='jtl_app.Spot'),
        ),
        migrations.AddField(
            model_name='jump',
            name='suit_id',
            field=models.ForeignKey(db_column='suit_id', on_delete=django.db.models.deletion.CASCADE, to='jtl_app.Suit'),
        ),
    ]
